/**
 * Renders `.hoh/README.md`, the human-readable development record (one section
 * per loop plus the ledger), and `tester_report.md` per loop.
 */
import { readFile, readdir } from "node:fs/promises";
import type { DeveloperRecord, EvidenceBundle, Ledger, PlannerRecord, RunConfig } from "../types.js";
import { coverageSummary, loadClaimCatalog, loadCoverage, renderCoverageTable } from "./coverage.js";
import { ledgerSummary, renderLedger } from "./ledger.js";
import { parseLoopDirName, readJson, RunPaths } from "./state.js";

interface LoopView {
  index: number;
  planner: PlannerRecord | null;
  developer: DeveloperRecord | null;
  evidence: EvidenceBundle | null;
  error: { message: string; role?: string } | null;
}

export async function collectLoops(paths: RunPaths): Promise<LoopView[]> {
  let entries: string[] = [];
  try {
    entries = await readdir(paths.iterations);
  } catch (error: any) {
    if (error?.code === "ENOENT") return [];
    throw error;
  }
  const views: LoopView[] = [];
  for (const name of entries) {
    const i = parseLoopDirName(name);
    if (i === null) continue;
    views.push({
      index: i,
      planner: await readJson<PlannerRecord>(paths.plannerJson(i)),
      developer: await readJson<DeveloperRecord>(paths.developerJson(i)),
      evidence: await readJson<EvidenceBundle>(paths.evidenceJson(i)),
      error: await readJson<{ message: string; role?: string }>(paths.errorJson(i)),
    });
  }
  return views.sort((a, b) => b.index - a.index);
}

function fmtTokens(n: number): string {
  return n >= 1_000_000 ? `${(n / 1_000_000).toFixed(2)}M` : n >= 1000 ? `${(n / 1000).toFixed(1)}k` : String(n);
}

export async function renderRunReadme(paths: RunPaths, run: RunConfig, ledger: Ledger): Promise<string> {
  const loops = await collectLoops(paths);
  const s = ledgerSummary(ledger);
  const spec = await readFile(paths.spec, "utf8");
  const catalog = await loadClaimCatalog(paths, spec);
  const coverage = catalog ? await loadCoverage(paths, catalog) : null;
  const lines: string[] = [];
  lines.push("# HoH Development Record", "");
  lines.push("<!-- generated by the HoH runtime from immutable loop records; do not edit -->", "");
  const models = run.config.models;
  const modelLine = (["planner", "developer", "tester"] as const)
    .map((r) => `${r}=${models[r] ?? models.default ?? "(harness default)"}`)
    .join(", ");
  lines.push(`**Run:** \`${run.run_id}\`  `);
  lines.push(`**Harness:** ${run.config.harness}  `);
  lines.push(`**Models:** ${modelLine}  `);
  lines.push(`**Workflow:** Project Planner → Developer → QA Tester  `);
  lines.push(`**Iteration budget:** ${run.config.loops}  `);
  lines.push(`**Config:** \`.hoh/config.json\` (from ${run.config_source})`, "");
  lines.push("---", "", "## Persistent issue ledger", "");
  lines.push("| Field | Value |", "| --- | --- |");
  lines.push(`| Open | ${s.open} |`, `| Regressed | ${s.regressed} |`, `| Closed | ${s.closed} |`, `| All | ${s.all} |`, "");
  lines.push(renderLedger(ledger), "");

  if (catalog && coverage) {
    const c = coverageSummary(catalog, coverage);
    lines.push("---", "", "## Fixed PRD coverage", "");
    lines.push(`**Verified ${c.verified} / Untested ${c.untested} / Gap ${c.gap} / All ${c.all}**`, "");
    lines.push(renderCoverageTable(catalog, coverage), "");
  }

  const latest = loops.find((l) => l.developer)?.developer?.candidate_id ?? "none";
  const bestVerified = loops.find((l) => l.evidence?.qa_status === "pass")?.evidence?.candidate_id ?? "none";
  lines.push("---", "", "## Current pointers", "");
  lines.push(`- Latest candidate: \`${latest}\``);
  lines.push(`- Best verified (last QA PASS): \`${bestVerified}\``);
  lines.push(`- Loops recorded: ${loops.length}`, "");

  for (const l of loops) {
    lines.push("---", "", `## Loop ${String(l.index).padStart(2, "0")}`, "");
    lines.push("> One Planner → Developer → QA Tester cycle recorded by the runtime.", "");
    lines.push("| Candidate | Base | QA |", "| --- | --- | --- |");
    lines.push(
      `| \`${l.developer?.candidate_id ?? "-"}\` | \`${l.planner?.base_candidate_id ?? "none"}\` | ${l.evidence ? l.evidence.qa_status.toUpperCase() : l.error ? "ERROR" : "UNTESTED"} |`,
      "",
    );
    if (l.planner) {
      lines.push("### Project Planner", "", "| Field | Value |", "| --- | --- |");
      lines.push(`| Objective | ${cell(l.planner.objective)} |`);
      lines.push(`| Priorities | ${l.planner.priorities.map((p) => cell(p.name)).join("; ")} |`);
      lines.push(`| Model | ${l.planner.usage.model ?? "-"} |`);
      lines.push(`| Tokens | ${fmtTokens(l.planner.usage.totalTokens)} (${l.planner.usage.turns} turns) |`, "");
    }
    if (l.developer) {
      lines.push("### Developer", "", "| Field | Value |", "| --- | --- |");
      lines.push(`| Commit | ${l.developer.commit ? `\`${l.developer.commit.slice(0, 12)}\`` : "no changes"} |`);
      lines.push(`| Changed paths | ${l.developer.changed_paths.length} |`);
      lines.push(`| Violations | ${l.developer.violations.length ? l.developer.violations.map(cell).join("; ") : "none"} |`);
      lines.push(`| Model | ${l.developer.usage.model ?? "-"} |`);
      lines.push(`| Tokens | ${fmtTokens(l.developer.usage.totalTokens)} (${l.developer.usage.turns} turns) |`, "");
    }
    if (l.evidence) {
      const e = l.evidence;
      lines.push("### QA Tester", "", "| Field | Value |", "| --- | --- |");
      lines.push(`| Status | ${e.qa_status.toUpperCase()} |`);
      lines.push(`| Frozen candidate | ${e.frozen ? "yes" : "NO (mutated during QA)"} |`);
      lines.push(`| Checks | ${e.checks.map((c) => `${c.name}=${c.status}`).join(", ") || "none"} |`);
      lines.push(`| Verified / gaps | ${e.verified_records.length} / ${e.gap_records.length} |`);
      lines.push(`| Model | ${e.usage.model ?? "-"} |`);
      lines.push(`| Tokens | ${fmtTokens(e.usage.totalTokens)} (${e.usage.turns} turns) |`, "");
      if (e.gap_records.length) {
        lines.push("#### Findings", "", "| ID | Severity | Claim |", "| --- | --- | --- |");
        for (const g of e.gap_records) lines.push(`| \`${g.claim_id}\` | ${g.severity ?? "-"} | ${cell(g.claim)} |`);
        lines.push("");
      }
    }
    if (l.error) {
      lines.push("### Error", "", "```", l.error.message, "```", "");
    }
  }
  return lines.join("\n");
}

export function renderTesterReport(e: EvidenceBundle): string {
  const lines: string[] = [];
  lines.push(`# QA report — loop ${e.loop_index}, candidate \`${e.candidate_id}\``, "");
  lines.push(`- Status: **${e.qa_status.toUpperCase()}**`);
  lines.push(`- Frozen: ${e.frozen ? "yes" : "NO"} (tree ${e.candidate_source_sha256_before.slice(0, 12)} → ${e.candidate_source_sha256_after.slice(0, 12)})`);
  lines.push(`- Summary: ${e.summary}`, "");
  lines.push("## Deterministic checks", "");
  lines.push(
    e.checks.length
      ? e.checks.map((c) => `- \`${c.name}\`: ${c.status} (exit ${c.exit_code ?? "-"}, ${(c.duration_ms / 1000).toFixed(1)}s)`).join("\n")
      : "_none configured_",
    "",
  );
  const section = (title: string, records: EvidenceBundle["verified_records"]) => {
    lines.push(`## ${title}`, "");
    if (!records.length) lines.push("_none_", "");
    for (const r of records) {
      lines.push(`### \`${r.claim_id}\`${r.severity ? ` [${r.severity}]` : ""}`, "", r.claim, "");
      for (const x of r.execution_records) {
        lines.push(`- ${x.type}${x.path ? ` \`${x.path}\`` : ""}${x.sha256 ? ` (sha256 ${x.sha256.slice(0, 12)})` : ""}: ${x.observation}`);
      }
      if (r.player_impact) lines.push(`- Player impact: ${r.player_impact}`);
      if (r.recommended_update) lines.push(`- Recommended update: ${r.recommended_update}`);
      lines.push("");
    }
  };
  section("Verified records", e.verified_records);
  section("Gap records", e.gap_records);
  lines.push("## Planner handoff", "");
  lines.push(`- Preserve: ${e.planner_handoff.preservation_constraints.join("; ") || "-"}`);
  lines.push(`- Update targets: ${e.planner_handoff.update_targets.join("; ") || "-"}`);
  lines.push(`- Validation: ${e.planner_handoff.validation_requirements.join("; ") || "-"}`);
  if (e.runtime_notes.length) {
    lines.push("", "## Runtime notes", "");
    for (const n of e.runtime_notes) lines.push(`- ${n}`);
  }
  return lines.join("\n");
}

function cell(s: string): string {
  return s.replace(/\|/g, "\\|").replace(/\s+/g, " ").trim();
}
