/**
 * Renders `.hoh/README.md`, the human-readable development record (one section
 * per loop plus the ledger), and `tester_report.md` per loop.
 */
import { readFile, readdir } from "node:fs/promises";
import type {
  BudgetLedger,
  BudgetMetric,
  ClaimCatalog,
  DeveloperRecord,
  EvidenceBundle,
  Ledger,
  PlannerRecord,
  Role,
  RoleUsage,
  RunConfig,
} from "../types.js";
import {
  applyCoverage,
  claimCatalogSha256,
  coverageSummary,
  emptyCoverage,
  loadClaimCatalog,
  loadCoverage,
  renderCoverageTable,
  type CoverageSummary,
} from "./coverage.js";
import { ledgerSummary, renderLedger } from "./ledger.js";
import { loadBudgetLedger, parseLoopDirName, readJson, RunPaths } from "./state.js";

interface LoopView {
  index: number;
  planner: PlannerRecord | null;
  developer: DeveloperRecord | null;
  evidence: EvidenceBundle | null;
  error: { message: string; role?: string } | null;
}

export interface RunReportOptions {
  /** A caller-supplied offline receipt check. Omission is reported as not checked. */
  receiptVerification?: {
    readonly ok: boolean;
    readonly issues?: readonly { readonly code: string }[];
  };
}

interface LedgerTransitions {
  opened: string[];
  reopened: string[];
  closed: string[];
}

export async function collectLoops(paths: RunPaths): Promise<LoopView[]> {
  let entries: string[] = [];
  try {
    entries = await readdir(paths.iterations);
  } catch (error: any) {
    if (error?.code === "ENOENT") return [];
    throw error;
  }
  const views: LoopView[] = [];
  for (const name of entries) {
    const i = parseLoopDirName(name);
    if (i === null) continue;
    views.push({
      index: i,
      planner: await readJson<PlannerRecord>(paths.plannerJson(i)),
      developer: await readJson<DeveloperRecord>(paths.developerJson(i)),
      evidence: await readJson<EvidenceBundle>(paths.evidenceJson(i)),
      error: await readJson<{ message: string; role?: string }>(paths.errorJson(i)),
    });
  }
  return views.sort((a, b) => b.index - a.index);
}

function fmtTokens(n: number): string {
  return n >= 1_000_000 ? `${(n / 1_000_000).toFixed(2)}M` : n >= 1000 ? `${(n / 1000).toFixed(1)}k` : String(n);
}

export async function renderRunReadme(
  paths: RunPaths,
  run: RunConfig,
  ledger: Ledger,
  options: RunReportOptions = {},
): Promise<string> {
  const loops = await collectLoops(paths);
  const budget = await loadBudgetLedger(paths);
  const s = ledgerSummary(ledger);
  const spec = await readFile(paths.spec, "utf8");
  const catalog = run.config.claim_catalog === "off" ? null : await loadClaimCatalog(paths, spec);
  const coverage = catalog ? await loadCoverage(paths, catalog) : null;
  const lines: string[] = [];
  lines.push("# HoH Development Record", "");
  lines.push("<!-- generated by the HoH runtime from immutable loop records; do not edit -->", "");
  const models = run.config.models;
  const modelLine = (["planner", "developer", "tester"] as const)
    .map((r) => `${r}=${models[r] ?? models.default ?? "(harness default)"}`)
    .join(", ");
  lines.push(`**Run:** \`${run.run_id}\`  `);
  lines.push(
    `**Protocol:** ${(run.protocol_receipt?.mode ?? run.config.protocol ?? "extended").toUpperCase()}${run.protocol_receipt?.legacy_default ? " (legacy default)" : ""}${run.protocol_receipt?.origin === "legacy_reconstruction" ? " (receipt reconstructed)" : ""}${run.protocol_receipt ? ` — \`${run.protocol_receipt.protocol_sha256}\`` : " (protocol receipt unavailable)"}  `,
  );
  lines.push(`**Harness:** ${run.config.harness}  `);
  lines.push(`**Configured models:** ${modelLine}  `);
  lines.push(`**Run receipt verification at report generation:** ${formatReceiptVerification(options.receiptVerification)}  `);
  lines.push(`**Workflow:** Project Planner → Developer → QA Tester  `);
  lines.push(`**Iteration budget:** ${run.config.loops}  `);
  if (run.protocol_receipt && run.protocol_receipt.initial_loops !== run.config.loops) {
    lines.push(`**Initial iteration budget:** ${run.protocol_receipt.initial_loops}  `);
  }
  lines.push(`**Config:** \`.hoh/config.json\` (from ${run.config_source})`, "");
  if (budget) renderBudgetSummary(lines, budget);
  lines.push("---", "", "## Persistent issue ledger", "");
  lines.push("| Field | Value |", "| --- | --- |");
  lines.push(`| Open | ${s.open} |`, `| Regressed | ${s.regressed} |`, `| Closed | ${s.closed} |`, `| All | ${s.all} |`, "");
  lines.push(renderLedger(ledger), "");

  if (catalog && coverage) {
    const c = coverageSummary(catalog, coverage);
    lines.push("---", "", "## Fixed PRD coverage", "");
    lines.push(`**Verified ${c.verified} / Untested ${c.untested} / Gap ${c.gap} / All ${c.all}**`, "");
    lines.push(renderCoverageTable(catalog, coverage), "");
  }

  renderLoopTrends(lines, loops, catalog, ledger);

  const latest = loops.find((l) => l.developer)?.developer?.candidate_id ?? "none";
  const bestVerified = loops.find((l) => l.evidence?.qa_status === "pass")?.evidence?.candidate_id ?? "none";
  lines.push("---", "", "## Current pointers", "");
  lines.push(`- Latest candidate: \`${latest}\``);
  lines.push(`- Best verified (last QA PASS): \`${bestVerified}\``);
  lines.push(`- Loops recorded: ${loops.length}`, "");

  for (const l of loops) {
    lines.push("---", "", `## Loop ${String(l.index).padStart(2, "0")}`, "");
    lines.push("> One Planner → Developer → QA Tester cycle recorded by the runtime.", "");
    lines.push("| Candidate | Base | QA |", "| --- | --- | --- |");
    lines.push(
      `| \`${l.developer?.candidate_id ?? "-"}\` | \`${l.planner?.base_candidate_id ?? "none"}\` | ${l.evidence ? l.evidence.qa_status.toUpperCase() : l.error ? "ERROR" : "UNTESTED"} |`,
      "",
    );
    if (l.planner) {
      const metrics = roleReportMetrics(budget, l.index, "planner", l.planner.usage);
      lines.push("### Project Planner", "", "| Field | Value |", "| --- | --- |");
      lines.push(`| Objective | ${cell(l.planner.objective)} |`);
      lines.push(`| Priorities | ${l.planner.priorities.map((p) => cell(p.name)).join("; ")} |`);
      lines.push(`| Resolved model | ${l.planner.usage.model ?? "-"} |`);
      lines.push(...roleUsageRows(metrics), "");
    }
    if (l.developer) {
      const metrics = roleReportMetrics(budget, l.index, "developer", l.developer.usage);
      lines.push("### Developer", "", "| Field | Value |", "| --- | --- |");
      lines.push(`| Commit | ${l.developer.commit ? `\`${l.developer.commit.slice(0, 12)}\`` : "no changes"} |`);
      lines.push(`| Changed paths | ${l.developer.changed_paths.length} |`);
      lines.push(`| Violations | ${l.developer.violations.length ? l.developer.violations.map(cell).join("; ") : "none"} |`);
      lines.push(`| Resolved model | ${l.developer.usage.model ?? "-"} |`);
      lines.push(...roleUsageRows(metrics), "");
    }
    if (l.evidence) {
      const e = l.evidence;
      const metrics = roleReportMetrics(budget, l.index, "tester", e.usage);
      lines.push("### QA Tester", "", "| Field | Value |", "| --- | --- |");
      lines.push(`| Status | ${e.qa_status.toUpperCase()} |`);
      lines.push(`| Frozen candidate | ${e.frozen ? "yes" : "NO (mutated during QA)"} |`);
      lines.push(`| Checks | ${e.checks.map((c) => `${c.name}=${c.status}`).join(", ") || "none"} |`);
      lines.push(`| Verified / gaps | ${e.verified_records.length} / ${e.gap_records.length} |`);
      lines.push(`| Records | ${loopRecordLinks(l.index)} |`);
      lines.push(`| Resolved model | ${e.usage.model ?? "-"} |`);
      lines.push(...roleUsageRows(metrics), "");
      if (e.gap_records.length) {
        lines.push("#### Findings", "", "| ID | Severity | Claim |", "| --- | --- | --- |");
        for (const g of e.gap_records) lines.push(`| \`${g.claim_id}\` | ${g.severity ?? "-"} | ${cell(g.claim)} |`);
        lines.push("");
      }
    }
    if (l.error) {
      lines.push("### Error", "", "```", l.error.message, "```", "");
    }
  }
  return lines.join("\n");
}

function renderLoopTrends(lines: string[], loops: LoopView[], catalog: ClaimCatalog | null, ledger: Ledger): void {
  const transitions = ledgerTransitionsByLoop(ledger);
  const coverage = loopCoverageTrends(loops, catalog);
  lines.push("---", "", "## Loop trends", "");
  lines.push(
    "| Loop | Verified | Gap | Untested | Opened | Reopened | Closed | Records |",
    "| ---: | ---: | ---: | ---: | --- | --- | --- | --- |",
  );
  for (const loop of [...loops].sort((a, b) => a.index - b.index)) {
    const counts = coverage.get(loop.index);
    const delta = transitions.get(loop.index) ?? emptyLedgerTransitions();
    lines.push(
      `| ${String(loop.index).padStart(2, "0")} | ${counts?.verified ?? "-"} | ${counts?.gap ?? "-"} | ${counts?.untested ?? "-"} | ${formatIds(delta.opened)} | ${formatIds(delta.reopened)} | ${formatIds(delta.closed)} | ${loop.evidence ? loopRecordLinks(loop.index) : "-"} |`,
    );
  }
  if (!loops.length) lines.push("| - | - | - | - | - | - | - | - |");
  lines.push("");
}

function loopCoverageTrends(loops: LoopView[], catalog: ClaimCatalog | null): Map<number, CoverageSummary> {
  const trends = new Map<number, CoverageSummary>();
  if (!catalog) return trends;
  let coverage = emptyCoverage(catalog);
  const catalogHash = claimCatalogSha256(catalog);
  for (const loop of [...loops].sort((a, b) => a.index - b.index)) {
    if (!loop.evidence || loop.evidence.claim_catalog_sha256 !== catalogHash) continue;
    coverage = applyCoverage(catalog, coverage, loop.evidence);
    trends.set(loop.index, coverageSummary(catalog, coverage));
  }
  return trends;
}

function ledgerTransitionsByLoop(ledger: Ledger): Map<number, LedgerTransitions> {
  const byLoop = new Map<number, LedgerTransitions>();
  const at = (loop: number) => {
    const current = byLoop.get(loop) ?? emptyLedgerTransitions();
    byLoop.set(loop, current);
    return current;
  };
  for (const issue of Object.values(ledger.issues)) {
    for (const event of issue.history) {
      if (event.status === "open") at(event.loop).opened.push(issue.id);
      if (event.status === "regressed") at(event.loop).reopened.push(issue.id);
      if (event.status === "closed") at(event.loop).closed.push(issue.id);
    }
  }
  for (const delta of byLoop.values()) {
    delta.opened.sort();
    delta.reopened.sort();
    delta.closed.sort();
  }
  return byLoop;
}

function emptyLedgerTransitions(): LedgerTransitions {
  return { opened: [], reopened: [], closed: [] };
}

function formatIds(ids: string[]): string {
  return ids.length ? ids.map(cell).join(", ") : "-";
}

function loopRecordLinks(loopIndex: number): string {
  const loop = `loop-${String(loopIndex).padStart(2, "0")}`;
  return `[evidence](iterations/${loop}/evidence.json) / [QA report](iterations/${loop}/tester_report.md)`;
}

function formatReceiptVerification(verification: RunReportOptions["receiptVerification"]): string {
  if (!verification) return "NOT CHECKED";
  if (verification.ok) return "VERIFIED";
  const codes = [...new Set((verification.issues ?? []).map((issue) => issue.code))].sort();
  const count = verification.issues?.length;
  const detail = codes.length ? `: ${codes.join(", ")}` : "";
  return `FAILED (${count === undefined ? "unknown" : count} issue${count === 1 ? "" : "s"}${detail})`;
}

interface RoleReportMetrics {
  attempts: number;
  usage: RoleUsage;
}

function roleReportMetrics(
  budget: BudgetLedger | null,
  loopIndex: number,
  role: Role,
  fallback: RoleUsage,
): RoleReportMetrics {
  const attempts = budget?.attempts.filter((attempt) => attempt.loop_index === loopIndex && attempt.role === role) ?? [];
  const charged = attempts.flatMap((attempt) => (attempt.usage ? [attempt.usage] : []));
  if (!charged.length) return { attempts: attempts.length || 1, usage: fallback };
  const accounted = Object.values(budget?.loops ?? {}).find((loop) => loop.loop_index === loopIndex)?.roles[role];
  const usage: RoleUsage = {
    input: 0,
    output: 0,
    cacheRead: 0,
    cacheWrite: 0,
    totalTokens: 0,
    cost: 0,
    turns: 0,
    duration_ms: 0,
  };
  for (const item of charged) {
    usage.input += item.input;
    usage.output += item.output;
    usage.cacheRead += item.cacheRead;
    usage.cacheWrite += item.cacheWrite;
    usage.totalTokens += item.totalTokens;
    usage.cost += item.cost;
    usage.turns += item.turns;
    usage.duration_ms += item.duration_ms;
    usage.retry_count = (usage.retry_count ?? 0) + (item.retry_count ?? 0);
    usage.compaction_count = (usage.compaction_count ?? 0) + (item.compaction_count ?? 0);
    usage.compaction_tokens_before = (usage.compaction_tokens_before ?? 0) + (item.compaction_tokens_before ?? 0);
    if (item.compaction_estimated_tokens_after !== undefined) {
      usage.compaction_estimated_tokens_after = item.compaction_estimated_tokens_after;
    }
  }
  if (accounted) {
    usage.duration_ms = accounted.elapsed_ms;
    usage.totalTokens = accounted.total_tokens;
    usage.cost = accounted.cost;
  }
  usage.model = fallback.model;
  return { attempts: attempts.length, usage };
}

function roleUsageRows(metrics: RoleReportMetrics): string[] {
  return [
    `| Duration | ${formatDuration(metrics.usage.duration_ms)} |`,
    `| Tokens | ${fmtTokens(metrics.usage.totalTokens)} (${metrics.usage.turns} turn${metrics.usage.turns === 1 ? "" : "s"}) |`,
    `| Cost | ${formatCost(metrics.usage.cost)} |`,
    `| Role attempts | ${metrics.attempts} |`,
    `| Transport retries | ${metrics.usage.retry_count ?? 0} |`,
    compactionUsageRow(metrics.usage),
  ];
}

function compactionUsageRow(usage: RoleUsage): string {
  if (!usage.compaction_count) return "| Compactions | 0 |";
  const before = fmtTokens(usage.compaction_tokens_before ?? 0);
  const after = usage.compaction_estimated_tokens_after === undefined ? "unknown" : fmtTokens(usage.compaction_estimated_tokens_after);
  return `| Compactions | ${usage.compaction_count ?? 0} (${before} before → ${after} estimated after) |`;
}

function renderBudgetSummary(lines: string[], budget: BudgetLedger): void {
  lines.push("---", "", "## Resource budget ledger", "");
  lines.push("| Field | Value |", "| --- | --- |");
  lines.push(`| Runtime status | ${budget.status.toUpperCase()} |`);
  lines.push(`| Run elapsed | ${formatDuration(budget.totals.elapsed_ms)} |`);
  lines.push(`| Run tokens | ${fmtTokens(budget.totals.total_tokens)} |`);
  lines.push(`| Run cost | ${formatCost(budget.totals.cost)} |`);
  lines.push(
    `| Current role | ${budget.current_role ? `loop ${String(budget.current_role.loop_index).padStart(2, "0")} / ${budget.current_role.role} (since ${budget.current_role.started_at})` : "none"} |`,
  );
  if (budget.exhaustion) {
    const exhaustion = budget.exhaustion;
    lines.push(
      `| Exhaustion | ${exhaustion.scope}${exhaustion.loop_index ? ` loop ${exhaustion.loop_index}` : ""}${exhaustion.role ? ` ${exhaustion.role}` : ""}: ${exhaustion.metric} ${formatBudgetMetric(exhaustion.metric, exhaustion.used)} / ${formatBudgetMetric(exhaustion.metric, exhaustion.limit)}${exhaustion.before_role ? `; blocked before ${exhaustion.before_role}` : ""} |`,
    );
  }
  lines.push("");

  lines.push("### Configured ceilings", "");
  lines.push("| Scope | Elapsed | Tokens | Cost |", "| --- | ---: | ---: | ---: |");
  for (const scope of ["role", "loop", "run"] as const) {
    const limit = budget.limits[scope];
    lines.push(
      `| ${scope} | ${limit?.elapsed_ms === undefined ? "unlimited" : formatDuration(limit.elapsed_ms)} | ${limit?.total_tokens === undefined ? "unlimited" : fmtTokens(limit.total_tokens)} | ${limit?.cost === undefined ? "unlimited" : formatCost(limit.cost)} |`,
    );
  }
  lines.push("");

  if (Object.keys(budget.loops).length) {
    lines.push("### Charged loop totals", "");
    lines.push("| Loop | Elapsed | Tokens | Cost |", "| ---: | ---: | ---: | ---: |");
    for (const loop of Object.values(budget.loops).sort((a, b) => a.loop_index - b.loop_index)) {
      lines.push(
        `| ${String(loop.loop_index).padStart(2, "0")} | ${formatDuration(loop.totals.elapsed_ms)} | ${fmtTokens(loop.totals.total_tokens)} | ${formatCost(loop.totals.cost)} |`,
      );
    }
    lines.push("");
  }
  lines.push(
    "Completed role usage is charged exactly as reported (including same-session Pi retries). A harness call that fails before returning usage is recorded as unavailable and is not estimated.",
    "",
  );
}

function formatDuration(durationMs: number): string {
  return `${(durationMs / 1000).toFixed(1)}s`;
}

function formatCost(cost: number): string {
  return `$${cost.toFixed(6)}`;
}

function formatBudgetMetric(metric: BudgetMetric, value: number): string {
  if (metric === "elapsed_ms") return formatDuration(value);
  if (metric === "total_tokens") return fmtTokens(value);
  return formatCost(value);
}

export function renderTesterReport(e: EvidenceBundle): string {
  const lines: string[] = [];
  lines.push(`# QA report — loop ${e.loop_index}, candidate \`${e.candidate_id}\``, "");
  lines.push(`- Status: **${e.qa_status.toUpperCase()}**`);
  lines.push(`- Frozen: ${e.frozen ? "yes" : "NO"} (tree ${e.candidate_source_sha256_before.slice(0, 12)} → ${e.candidate_source_sha256_after.slice(0, 12)})`);
  lines.push(`- Summary: ${e.summary}`, "");
  lines.push("## Deterministic checks", "");
  lines.push(
    e.checks.length
      ? e.checks.map((c) => `- \`${c.name}\`: ${c.status} (exit ${c.exit_code ?? "-"}, ${(c.duration_ms / 1000).toFixed(1)}s)`).join("\n")
      : "_none configured_",
    "",
  );
  const section = (title: string, records: EvidenceBundle["verified_records"]) => {
    lines.push(`## ${title}`, "");
    if (!records.length) lines.push("_none_", "");
    for (const r of records) {
      lines.push(`### \`${r.claim_id}\`${r.severity ? ` [${r.severity}]` : ""}`, "", r.claim, "");
      for (const x of r.execution_records) {
        lines.push(`- ${x.type}${x.path ? ` \`${x.path}\`` : ""}${x.sha256 ? ` (sha256 ${x.sha256.slice(0, 12)})` : ""}: ${x.observation}`);
      }
      if (r.player_impact) lines.push(`- Player impact: ${r.player_impact}`);
      if (r.recommended_update) lines.push(`- Recommended update: ${r.recommended_update}`);
      lines.push("");
    }
  };
  section("Verified records", e.verified_records);
  section("Gap records", e.gap_records);
  lines.push("## Planner handoff", "");
  lines.push(`- Preserve: ${e.planner_handoff.preservation_constraints.join("; ") || "-"}`);
  lines.push(`- Update targets: ${e.planner_handoff.update_targets.join("; ") || "-"}`);
  lines.push(`- Validation: ${e.planner_handoff.validation_requirements.join("; ") || "-"}`);
  if (e.runtime_notes.length) {
    lines.push("", "## Runtime notes", "");
    for (const n of e.runtime_notes) lines.push(`- ${n}`);
  }
  return lines.join("\n");
}

function cell(s: string): string {
  return s.replace(/\|/g, "\\|").replace(/\s+/g, " ").trim();
}
